site_name: embEDUx Doc
theme:
  readthedocs
use_directory_urls: false
docs_dir: '.'
pages:
- ['background.md', 'embEDUx']
- ['usage.md', 'embEDUx']
- ['home.md', 'embEDUx']
- ['setup.md', 'embEDUx']
- ['background/Terminology.md', 'background']
- ['background/flashtool.md', 'background']
- ['background/linux.md', 'background']
- ['background/misc.md', 'background']
- ['background/rootfs.md', 'background']
- ['background/uboot.md', 'background']
- ['background/common.md', 'background']
- ['background/common/requirements.md', 'background/common']
- ['setup/user-documentation.md', 'setup']
- ['setup/flashtool.md', 'setup']
- ['setup/linux.md', 'setup']
- ['setup/misc.md', 'setup']
- ['setup/rootfs.md', 'setup']
- ['setup/uboot.md', 'setup']
- ['setup/buildslaves-add-packages.md', 'setup']
- ['setup/examples/user-documentation.md', 'setup/examples']
- ['usage/flashtool.md', 'usage']
- ['usage/linux.md', 'usage']
- ['usage/misc.md', 'usage']
- ['usage/rootfs.md', 'usage']
- ['usage/toolchains.md', 'usage']
- ['usage/uboot.md', 'usage']
- ['usage/rootfs/run-as-container.md', 'usage/rootfs']
- ['usage/common/build-monitoring.md', 'usage/common']
- ['usage/common/repositories.md', 'usage/common']
